#!/bin/bash

FILE=/var/local/myip.txt
if ! [ -e $FILE ]; then
    sudo touch /var/local/myip.txt
    sudo chmod 777 /var/local/myip.txt 
fi
CURRENTIP=`curl ifconfig.co`
SAVEDIP=`cat $FILE`

if [[ $CURRENTIP != $SAVEDIP ]]; then
    echo $CURRENTIP | xargs send_email.py "Change Notification"
    echo $CURRENTIP > $FILE
fi
