#!/bin/bash

FILE=/var/local/myip.txt
CURRENTIP=`curl icanhazip.com`
SAVEDIP=`cat $FILE`

if [[ $CURRENTIP != $SAVEDIP ]]; then
    echo $CURRENTIP | xargs send_email.py "Routine Report"
    echo $CURRENTIP > $FILE
fi
